# Generated by Django 6.0.6 on 2026-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fetched_at', models.DateTimeField()),
                ('record_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_id', models.IntegerField(db_index=True, unique=True)),
                ('proceso_id', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=50)),
                ('nombre_solicitante', models.CharField(max_length=255)),
                ('email_solicitante', models.CharField(max_length=255)),
                ('titulo_investigacion', models.TextField(blank=True)),
                ('texto_clasificacion', models.TextField(blank=True)),
                ('colecta_muestras', models.CharField(blank=True, max_length=500)),
                ('fecha_termino_actividades', models.CharField(max_length=20)),
                ('anios_transcurridos', models.FloatField()),
                ('fecha_modificacion', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('regiones_list', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['fecha_termino_actividades'],
            },
        ),
        migrations.CreateModel(
            name='PortadaHistoricoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramite_id', models.IntegerField(db_index=True, unique=True)),
                ('proceso_id', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('nombre_solicitante', models.CharField(max_length=255)),
                ('email_solicitante', models.CharField(max_length=255)),
                ('titulo_investigacion', models.TextField(blank=True)),
                ('texto_clasificacion', models.TextField(blank=True)),
                ('regiones_list', models.JSONField(default=list)),
                ('fecha_inicio', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
